name: First Learning
on: workflow_dispatch
jobs:
    test-job:
        runs-on: windows-latest
        steps:
            - name: Setup Nodejs
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Run this command
              run: echo "runned successfully"
                
