name: React Project
on: [push,workflow_dispatch]
jobs: 
  test:
   runs-on: windows-latest
   steps:
    - name: checkout the file
      uses: actions/checkout@v3
    - name: "Created a new file"
      run: echo "New file is created"
    - name: Install Dependies
      run: npm ci 
    - name: Install test
      run: npm test
  deploy:
     needs: test
     runs-on: windows-latest
     steps:
      - name: Testing insure
        run: echo "Runned Successfully"
