name: learning-Basic
on: workflow_dispatch
jobs:
  test:
   runs-on: windows-latest
   steps:
     - name: Output Github
       run: echo "{{ toJSON(github) }}"
  something:
    needs: test
    runs-on: windows-latest
    steps:
      - name: SOmething
        run: echo "Hello" 

  
